### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by mrjlynch** [jhjguxin/mongoid-sequence2#2]
I am getting the following error when installing rails 4

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    mongoid-sequence2 (>= 0) ruby depends on
      activesupport (<= 4.0, >= 3.0.0) ruby

    rails (~> 4.0.0) ruby depends on
      activesupport (4.0.2)

**Comment by jhjguxin** [comment]
sorry long time to wait, @mrjlynch version `0.4.0` released
